Fixed: build window log error
Compiling serde_yaml v0.9.34+deprecated
   Compiling env_logger v0.11.8
   Compiling futures v0.3.31
error: failed to run custom build command for `claudia v0.1.0 (D:\a\claudia\claudia\src-tauri)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `D:\a\claudia\claudia\src-tauri\target\debug\build\claudia-454e50726540d1fd\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rustc-check-cfg=cfg(desktop)
  cargo:rustc-cfg=desktop
  cargo:rustc-check-cfg=cfg(mobile)
  cargo:rerun-if-changed=D:\a\claudia\claudia\src-tauri\tauri.conf.json
  cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_APP_NAME=so
  cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_PREFIX=claudia_asterisk
  cargo:rustc-check-cfg=cfg(dev)
  cargo:PERMISSION_FILES_PATH=D:\a\claudia\claudia\src-tauri\target\debug\build\claudia-4a57c6331759bab6\out\app-manifest\__app__-permission-files
  cargo:rerun-if-changed=capabilities
  cargo:rerun-if-env-changed=REMOVE_UNUSED_COMMANDS
  cargo:rustc-env=TAURI_ENV_TARGET_TRIPLE=x86_64-pc-windows-msvc
  cargo:rerun-if-changed=binaries\claude-code-x86_64-pc-windows-msvc.exe
  package.metadata does not exist
  Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
  Copyright (C) Microsoft Corporation.  All rights reserved.

  D:\a\claudia\claudia\src-tauri\target\debug\build\claudia-4a57c6331759bab6\out\resource.rc(26) : error RC2175 : resource file \\?\D:\a\claudia\claudia\src-tauri\icons\icon.ico is not in 3.00 format

  --- stderr

  thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-winres-0.3.1\src\lib.rs:537:14:
  called `Result::unwrap()` on an `Err` value: Failed("RC.EXE failed to compile specified resource file")
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\panicking.rs:697
     1: core::panicking::panic_fmt
               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\core\src\panicking.rs:75
     2: core::result::unwrap_failed
               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\core\src\result.rs:1732
     3: tauri_winres::WindowsResource::compile
     4: tauri_build::try_build
     5: tauri_build::build
     6: std::rt::lang_start
     7: std::rt::lang_start
     8: std::rt::lang_start
     9: std::rt::lang_start
    10: std::rt::lang_start_internal::closure$0
               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\rt.rs:168
    11: std::panicking::try::do_call
               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\panicking.rs:589
    12: std::panicking::try
               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\panicking.rs:552
    13: std::panic::catch_unwind
               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\panic.rs:359
    14: std::rt::lang_start_internal
               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\rt.rs:164
    15: std::rt::lang_start
    16: main
    17: invoke_main
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    18: __scrt_common_main_seh
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    19: BaseThreadInitThunk